
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ERROR = "GET_ERROR";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CREATE_BRAND = "CREATE_BRAND";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"; 
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
export const GET_PRODUCTS_LIKE = "GET_PRODUCTS_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";