
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ERROR = "GET_ERROR";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CREATE_BRAND = "CREATE_BRAND";